name: Build and Test Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build and Test using Docker
        run: |
          docker build -t card-validation .
          docker run --rm card-validation
          
      - name: Upload test results
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: test-results.xml

  upload-test-report:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Download test results
        uses: actions/download-artifact@v2
        with:
          name: test-results
          path: ./test-results

      - name: Publish test results
        uses: jamesives/github-issue-creator@v1
        with:
          result-file: './test-results/test-results.xml'
