name: Build, Test, and Deploy with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
        docker build -t qa-home-assignement .

    - name: Run Docker container
      run: |
        docker run -d -p 8080:80 --name qa-home-container qa-home-assignement

    - name: Run tests inside Docker container
      run: |
        docker exec -it qa-home-container bash -c "dotnet test /app/CardValidation.Tests/ --logger 'trx;LogFileName=test-results.trx'"

    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: test-results.trx
