name: Build, Test, and Deploy with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout repository
      uses: actions/checkout@v2

    # Set up Docker Buildx 
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Build the Docker image (including application and tests)
    - name: Build Docker image
      run: |
        docker build -t qa-home-assignement .
    # Run the Docker container in detached mode
    - name: Run Docker container
      run: |
        docker run -d -p 8080:80 qa-home-assignement
    # Run tests inside the same Docker container
    - name: Run tests inside Docker container
      run: |
        docker exec $(docker ps -q --filter "ancestor=qa-home-assignement") bash -c "dotnet test /app/CardValidation.Tests/ --logger 'trx;LogFileName=test-results.trx'"
    # Upload test results as an artifact
    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: test-results.trx