jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET Core SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0'

      - name: Install dependencies
        run: |
          dotnet restore

      - name: Build the project
        run: |
          dotnet build

      - name: Run unit tests
        run: |
          dotnet test --logger "xunit;LogFileName=test-results.xml"

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test-results.xml
